const SUCCESS_OK = 200;
const ERROR_INVALID_DATA = 400;
const AUTENTICATION_ERROR = 401;
const FORBIDDEN_ERROR = 403;
const ERROR_NOT_FOUND = 404;
const CONFLICT_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;

module.exports = {
  SUCCESS_OK,
  ERROR_INVALID_DATA,
  AUTENTICATION_ERROR,
  FORBIDDEN_ERROR,
  ERROR_NOT_FOUND,
  CONFLICT_ERROR,
  INTERNAL_SERVER_ERROR,
};
